"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([[390],{

/***/ 96390:
/*!*************************************************!*\
  !*** ./src/.umi-production/core/EmptyRoute.tsx ***!
  \*************************************************/
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": function() { return /* binding */ EmptyRoute; }
/* harmony export */ });
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ 62435);
/* harmony import */ var umi__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! umi */ 3410);
/* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! react/jsx-runtime */ 86074);
// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!



function EmptyRoute() {
  var context = (0,umi__WEBPACK_IMPORTED_MODULE_1__/* .useOutletContext */ .bx)();
  return /*#__PURE__*/(0,react_jsx_runtime__WEBPACK_IMPORTED_MODULE_2__.jsx)(umi__WEBPACK_IMPORTED_MODULE_1__/* .Outlet */ .j3, {
    context: context
  });
}

/***/ })

}]);